name: myprofile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shimmer: ^1.1.0
  animated_text_kit: ^3.0.0
  cached_network_image: ^2.4.0
  font_awesome_flutter: ^8.11.0 
  intro_slider: ^2.3.4
  shared_preferences: ^0.5.12
  provider: ^4.0.0
  geolocator: ^6.1.12
  flutter_map: ^0.11.0
  latlng: ^0.0.2
  curved_navigation_bar: ^0.3.7
  share: ^0.6.2
  carousel_slider: ^3.0.0
  image_picker: ^0.6.3+4
  flutter_form_builder: ^4.0.1
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

 
  assets:
    - images/katherine.jpg
    - images/fruits.jpg
    - images/bicycle.jpg
    - images/shoe.jpg
    - images/shoe3.jpg
    - images/shoe2.jpg
    - images/esawa.jpg
    - images/nesewa.png
    - images/fonepay.png
    - images/white.jpg
    - images/khalti.png
    - images/clock.png
    - images/time.png
    - images/pays.png
    - images/payment.png
    - images/locations.png
    - images/intive.jpg
   
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
 
    - family: RoboroM
      fonts:
        - asset: fonts/Roboto-Medium.ttf
 