name: myprofile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  animated_text_kit: ^3.0.0
  cached_network_image: ^2.4.0
  font_awesome_flutter: ^8.11.0 
  intro_slider: ^2.3.4
  shared_preferences: ^0.5.12
  provider: ^4.0.0
  geolocator: ^6.1.12
 

  
 
  carousel_slider: ^3.0.0
  image_picker: ^0.6.3+4
 
  flutter_form_builder: ^4.0.1
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

 
  assets:
    - images/katherine.jpg
    - images/fruits.jpg
    - images/bicycle.jpg
    - images/shoe.jpg
    - images/shoe3.jpg
    - images/shoe2.jpg
    - images/esawa.jpg
    - images/nesewa.png
    - images/fonepay.png
    - images/white.jpg
    - images/khalti.png


    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: RoboroM
      fonts:
        - asset: fonts/Roboto-Medium.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
